;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        elpy-nav-backward-indent
        elpy-nav-forward-indent
        elpy-open-and-indent-line-below
        indent-for-tab-command
        latex-do-everything
        org-self-insert-command
        suspend-frame
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
